### ISSUE TITLE
Estilos

### ISSUE THREAD

**Issue by ericsuarez** [ULL-ESIT-GRADOII-DSI/ajax-ecma6-ficheros-ericconi#3]
Mejorar los estilos por defecto @Alu0100673647

**Comment by ericsuarez** [comment]
si puedes usa bootstrap o materialize

**Comment by Alu0100673647** [comment]
Hola @alu0100786330 he añadido estilo con sass 18ce515fc394476d6d19c4633654aa7666a17509
